name: CI
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        include:
          - sbt: 1.9.8
            java: 11
          - sbt: 1.9.8
            java: 17
          - sbt: 1.9.9
            java: 11
          - sbt: 1.9.9
            java: 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - name: Build
        shell: bash
        run: |
          echo "sbt.version=${{ matrix.sbt }}" > project/build.properties
          sbt test
